# Generated by Django 5.2.13 on 2026-06-08 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(max_length=160, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento de pago',
                'verbose_name_plural': 'eventos de pago',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Prueba'), ('starter', 'Inicial'), ('professional', 'Profesional')], default='trial', max_length=24)),
                ('status', models.CharField(choices=[('trialing', 'En prueba'), ('active', 'Activa'), ('past_due', 'Pago pendiente'), ('cancelled', 'Cancelada')], default='trialing', max_length=24)),
                ('provider_customer_id', models.CharField(blank=True, max_length=120)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=120)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'suscripción',
                'verbose_name_plural': 'suscripciones',
            },
        ),
    ]
