# Generated by Django 5.2.13 on 2026-08-02 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='past_due_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider_last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider_price_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'En prueba'), ('active', 'Activa'), ('past_due', 'Pago pendiente'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='trialing', max_length=24),
        ),
        migrations.CreateModel(
            name='BillingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=60)),
                ('reference_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='billing.subscription')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subscription', 'notification_type', 'reference_date'), name='unique_billing_notification')],
            },
        ),
    ]
