# Generated by Django 5.2.13 on 2026-06-08 23:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('approved', 'Aprobado'), ('invoiced', 'Facturado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('labor_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='mano de obra')),
                ('items_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='descuento')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válido hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='organizations.organization')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.vehicle')),
            ],
            options={
                'verbose_name': 'presupuesto',
                'verbose_name_plural': 'presupuestos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=240, verbose_name='descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='precio unitario')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='posición')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote')),
            ],
            options={
                'verbose_name': 'ítem de presupuesto',
                'verbose_name_plural': 'ítems de presupuesto',
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['organization', 'status'], name='quotes_quot_organiz_9b4c15_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['organization', 'created_at'], name='quotes_quot_organiz_589a48_idx'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='unique_quote_number_per_organization'),
        ),
    ]
