# Generated by Django 5.2.13 on 2026-06-09 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_vehicle_is_active'),
        ('organizations', '0002_alter_membership_options'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='legacy_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='quote',
            name='legacy_source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_id', ''), _negated=True), fields=('organization', 'legacy_source', 'legacy_id'), name='unique_legacy_quote_per_organization'),
        ),
    ]
