# Generated by Django 5.2.13 on 2026-08-02 15:54

import django.db.models.deletion
from datetime import timedelta
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_commercial_fields(apps, schema_editor):
    Quote = apps.get_model("quotes", "Quote")
    for quote in Quote.objects.select_related(
        "organization", "customer", "vehicle"
    ).iterator():
        organization = quote.organization
        quote.number_prefix = organization.quote_prefix
        quote.currency = organization.currency
        quote.share_expires_at = timezone.now() + timedelta(
            days=organization.public_quote_valid_days
        )
        if quote.status != "draft":
            vehicle = ""
            if quote.vehicle:
                vehicle = quote.vehicle.license_plate or " ".join(
                    value for value in (quote.vehicle.make, quote.vehicle.model) if value
                )
            items = list(quote.items.all())
            quote.issued_at = quote.created_at
            quote.issue_snapshot = {
                "organization": {
                    "name": organization.name,
                    "legal_name": organization.legal_name,
                    "business_type": organization.business_type,
                    "phone": organization.phone,
                    "email": organization.email,
                    "tax_id": organization.tax_id,
                    "address": organization.address,
                    "city": organization.city,
                    "country": organization.country,
                    "terms": organization.default_quote_terms,
                    "warranty": organization.default_warranty_text,
                    "payment_terms": organization.default_payment_terms,
                    "footer": organization.default_footer,
                },
                "customer": {
                    "name": quote.customer.name,
                    "phone": quote.customer.phone,
                    "email": quote.customer.email,
                    "tax_id": quote.customer.tax_id,
                    "address": quote.customer.address,
                },
                "vehicle": vehicle,
                "items": [
                    {
                        "description": item.description,
                        "quantity": str(item.quantity),
                        "unit_price": str(item.unit_price),
                        "total_amount": str(item.quantity * item.unit_price),
                    }
                    for item in items
                ],
                "amounts": {
                    "labor": str(quote.labor_amount),
                    "items": str(quote.items_amount),
                    "discount": str(quote.discount_amount),
                    "total": str(quote.total_amount),
                },
                "notes": quote.notes,
                "valid_until": quote.valid_until.isoformat() if quote.valid_until else "",
                "currency": quote.currency,
                "number": f"{quote.number_prefix}-{quote.number:06d}",
            }
        quote.public_access_enabled = quote.status != "draft"
        quote.save(
            update_fields=(
                "number_prefix",
                "currency",
                "share_expires_at",
                "issued_at",
                "issue_snapshot",
                "public_access_enabled",
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_share_token'),
        ('organizations', '0004_organization_city_organization_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.CharField(default='BRL', max_length=3),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='issue_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quote',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='number_prefix',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='quote',
            name='public_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='share_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='source_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='quotes.quote'),
        ),
        migrations.RunPython(backfill_commercial_fields, migrations.RunPython.noop),
        migrations.CreateModel(
            name='QuoteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_events', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quotes.quote')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['quote', 'created_at'], name='quotes_quot_quote_i_85b6f2_idx')],
            },
        ),
    ]
