# Generated by Django 5.2.13 on 2026-06-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ('organization__name', 'user__email'), 'verbose_name': 'membresía', 'verbose_name_plural': 'membresías'},
        ),
    ]
