# Generated by Django 5.2.13 on 2026-08-02 15:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organization_business_type_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('BR', 'Brasil'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('DO', 'República Dominicana'), ('EC', 'Ecuador'), ('SV', 'El Salvador'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'México'), ('NI', 'Nicaragua'), ('PA', 'Panamá'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('OT', 'Otro')], default='BR', max_length=2, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(choices=[('ARS', 'ARS'), ('BOB', 'BOB'), ('BRL', 'BRL'), ('CLP', 'CLP'), ('COP', 'COP'), ('CRC', 'CRC'), ('DOP', 'DOP'), ('GTQ', 'GTQ'), ('HNL', 'HNL'), ('MXN', 'MXN'), ('NIO', 'NIO'), ('PAB', 'PAB'), ('PEN', 'PEN'), ('PYG', 'PYG'), ('USD', 'USD'), ('UYU', 'UYU'), ('VES', 'VES')], default='BRL', max_length=3, verbose_name='moneda'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_footer',
            field=models.CharField(blank=True, max_length=240, verbose_name='pie de documento'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_payment_terms',
            field=models.TextField(blank=True, verbose_name='condiciones de pago'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_quote_terms',
            field=models.TextField(blank=True, verbose_name='condiciones del presupuesto'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_warranty_text',
            field=models.TextField(blank=True, verbose_name='garantía'),
        ),
        migrations.AddField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='razón social'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_content_type',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_filename',
            field=models.CharField(blank=True, editable=False, max_length=180),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='public_quote_valid_days',
            field=models.PositiveSmallIntegerField(default=90, verbose_name='vigencia del enlace público en días'),
        ),
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='America/Sao_Paulo', max_length=64, verbose_name='zona horaria'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='quote_prefix',
            field=models.CharField(default='PRES', max_length=12, validators=[django.core.validators.RegexValidator(message='Usa únicamente letras, números y guiones.', regex='^[A-Za-z0-9-]+$')], verbose_name='prefijo de presupuesto'),
        ),
        migrations.CreateModel(
            name='OrganizationDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_after', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_request', to='organizations.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('execute_after',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'created_at'], name='organizatio_organiz_fcb26f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Propietario'), ('admin', 'Administrador'), ('member', 'Colaborador')], default='member', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_invitations_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', 'email'], name='organizatio_organiz_f35a05_idx')],
            },
        ),
    ]
